# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c05ff83611020347574f2261ae1087062ce72bab1b32b813f3e3a0b1269ffdba2cc7b4732e8f241a5ebaae258da2880d7e3b4bcf0971425a4a385d2c8df91723

test:
  secret_key_base: 88adfa67a026b84c32d617f5f56c06e514a9bf9057a8586597a18248d8fb1895357e2404c4e388b308340c5a7c3976eeed71a20b4f1f3ad9882e40175cc2b50c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
